name: Build Maven Package

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK v21
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir releases && cp target/*.jar releases

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: releases

